### PR TITLE
 Make elements slide into view as you scroll down the page issue #1 […

### PR DESCRIPTION
**Pull request by rcoffie**
…skip ci]
 Make elements slide into view as you scroll down the page issue #1

### CODE REVIEW

**Comment by rcoffie** [comment]
https://user-images.githubusercontent.com/34107104/207237408-37f5c5e7-cdb1-4f28-a9e6-951fe893b2c5.mp4

**Comment by timlinux** [comment]
Confused here @rcoffie 😀 

1. What is this video showing 
2. Please use a proper screen recorder like licecap or peek

**Comment by rcoffie** [comment]
> 2\. licecap

**Peek keeps on crashing , actuaally i have tried every screen recorder on ubuntu and nothing seems to work for me either unsupported format or it keeps crashing**

**Comment by rcoffie** [comment]
> Confused here @rcoffie grinning
> 
>     1. What is this video showing
> 
>     2. Please use a proper screen recorder like licecap or peek
`


> Confused here @rcoffie grinning
> 
>     1. What is this video showing
> 
>     2. Please use a proper screen recorder like licecap or peek

**File type is mp4**
file-type


**Error message i get when uploading**
video-error

**Pull request closed without merging**
