### PR TITLE
Task to update news bar

### PR DESCRIPTION
**Pull request by Xpirix**
Fix for #445 and proposed fix according to https://github.com/qgis/QGIS-Website/issues/445#issuecomment-2381116869

- Removed https://github.com/qgis/QGIS-Website/blob/fd58eaf50d255f7d34412f0fb508f7a107a378b4/content/news/amy.md
- Added a task to fetch the latest first item from feed.qgis.org
- Show the fetched item in the news bar

image

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM - automation with gh would be great.

@anitagraser CC for you - hopefully this explains how to add a news banner to the site now.

**Comment by anitagraser** [comment]
So to summarize: whenever the website is built, the last entry from the feed is fetched and displayed?

**Comment by Xpirix** [comment]
@anitagraser , Yes, that's right. The JSON from https://feed.qgis.org/?lang=en&json=1 is fetched every 12 hours and then displayed on the website when we build.

**Comment by EmHain8** [comment]
1. I know the Text comes directly from the old site, but I think it can be updated to be more effective. The 'There' confuses me. Perhaps change it to "Click [here](link) to access plugins ready to be used."
2. Add in some information about the category of plugins or is this accessed somewhere else e.g. Stable, Experimental, QGIS server plugin, Depreciated. 
3. I don't know if this is the right place, but I wonder if we could write something about if a plugin is depreciated and you want to revive it, how you go about doing that?

Otherwise I love the new Plugin Portal! Great work and thank-you.

**Comment by Xpirix** [comment]
Thanks for the review @EmHain8, they are well noted. I will improve the plugin's website accordingly.

> I don't know if this is the right place, but I wonder if we could write something about if a plugin is depreciated and you want to revive it, how you go about doing that?

For now, we only have the documentation about publishing a plugin on the Plugin website (https://staging.plugins.qgis.org/publish/). But I think it's a great idea and it would be useful to add that to the website along with other documentation about plugin management. I'm thinking about adding a "Documentation > Manage a plugin" menu and including the documentation about reviving a deprecated as a submenu for example.

image

Please feel free to add a comment on the PR at https://github.com/Xpirix/QGIS-Plugins-Website/pull/5 if you have any questions or other suggestions.

**Comment by Xpirix** [comment]
I have also created a new issue for the Documentation part at https://github.com/Xpirix/QGIS-Plugins-Website/issues/20

**Pull request merged**
