### PR TITLE
Show current point release on roadmap

### PR DESCRIPTION
**Pull request by mbernasocchi**
Ther roadmap gives all information regarding release versions but it is not immediately evident which are the current point release.
image

This PR adds the point release number to the ribbon.
image

## Summary by CodeRabbit

- **New Features**
	- Updated the display of Long Term Release and Latest Release version information for improved clarity.
	- Enhanced naming conventions for version variables to better reflect the data being presented.

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@Xpirix I hope to have gotten the right variables (first HUGO commit for me), I could not test the build yet since the repo clone is failing me on some network issues.

**Review by jef-n — APPROVED** [review]

**Comment by timlinux** [comment]
LGTM thanks

**Comment by timlinux** [comment]
@Xpirix btw can we get rid of this code rabbit thing? I dont think it adds any value to our lives...

**Comment by Xpirix** [comment]
@timlinux sure. However, I don't think to have the right permission. I tried to update the access but it returns the following error:
image

**Comment by jef-n** [comment]
> @Xpirix btw can we get rid of this code rabbit thing? I dont think it adds any value to our lives...

@timlinux suspended

**Pull request merged**
