### PR TITLE
Contributing maps and screenshots from community

### PR DESCRIPTION
**Pull request by spatialthoughts**
Hello from the QGIS Contributor Meeting in Bratislava!

We are a group of QGIS users who would like to contribute some images and screenshot for the QGIS Website. These images can be used to demonstrate the capability and versatility of QGIS. 

The images have been resized and converted to Webp format for images and GIF for animations.

The images are contributed by 
1. Kurt Menke [@goemenke](https://github.com/geomenke)
2. Hans van der Kwast [@jvdkwast](https://github.com/jvdkwast)
3. Ujaval Gandhi [@spatialthoughts](https://github.com/spatialthoughts/)

Happy to update these as per different size/specifications if required.

### CODE REVIEW

**Comment by Xpirix** [comment]
Looks good to me. Thank you @spatialthoughts , @geomenke and @jvdkwast. 

I think these maps should fit into the website. You are right on keeping the image size optimal especially for the homepage.
The GIF should be okay also. We can always implement a lazy loader for them if needed.

**Comment by spatialthoughts** [comment]
Thank you @Xpirix for the review. I received more contributions from Steven Kim [@geographyclub](https://github.com/geographyclub) which are ideal for the homepage.

I have added 3 more files to this PR. All the contributed images can be used anywhere in the website.  For the homepage, I would specifically recommend the following options. 

* Create Maps: Replace the current image with either of   `main-create1.webp` ,  `main-create2.webp` or  `main-create3.webp`.
* Edit Layers: Replace the current image with `profile.webp`.
* Process and Analyze: Replace the current image with `model.webp`.
* Share Maps: Replace the current image with `layout.webp`.

**Comment by Xpirix** [comment]
Thanks for the suggestions @spatialthoughts and thanks for all who contributed too. I will submit a new PR for these.

However, for the Edit Layers image, another suggestion was also made by @andreasneumann at https://github.com/qgis/QGIS-Website/pull/429. I wonder which one should we keep for this section @spatialthoughts and @andreasneumann ?

**Comment by andreasneumann** [comment]
The one I provided suits better. It is really about editing tools. The other one submitted is about the profile tool. It could be used somewhere else, if needed.

I think we should remove the old images we don't use anymore.

Also - what is the point of keeping both the png and the webp version, if the webp is stored with lossless compression?

**Comment by Xpirix** [comment]
Yes, I also think it's better to remove the unused images.

**Pull request merged**
