### PR TITLE
Webp biggest images

### PR DESCRIPTION
**Pull request by haubourg**
@Xpirix I used Chromium "LightHouse" auditing tools to catch the heaviest images on first page load. 
This PR converts them to webp.

I tried also a full png/jpeg > webp conversion, as this is a bit trickier to be sure I wouldn't brake some pages. So I started small. 

Does this look good to you ?

## Summary by CodeRabbit

- **New Features**
	- Updated image formats from `.jpg` and `.png` to `.webp` for enhanced performance and quality.
	- Improved loading speed and visual fidelity of images on the webpage.

### CODE REVIEW

**Comment by Xpirix** [comment]
Looks good to me, thanks @haubourg 

I've merged this into my repo (https://xpirix.github.io/QGIS-Hugo/) and it works perfectly. 

I also confirm that the page performance increased. Please find the results at https://pagespeed.web.dev/analysis/https-xpirix-github-io-QGIS-Hugo/4brpmumxi9?form_factor=desktop. For the current version of the website, the performance test is available at https://pagespeed.web.dev/analysis/https-qgis-org/m75zf2xx91?form_factor=desktop

image

**Comment by haubourg** [comment]
Cool! 
I see other tips in Lighthouse but we made the easy 80% optimization here. 

Side note, git index is huge for a static website. What do you think of running repo cleaner ? Better early than later as long as we don't have too much PR pending.

**Comment by Xpirix** [comment]
I think that running a repo cleaner can be a good solution. A lighter Git repository can improve operations and decrease storage requirements.

However, some points should be taken into consideration (according to ChatGPT):

- Impact on History: Cleaning your repository rewrites its history, which can disrupt workflows. Ensure all team members are aware of the changes and rebase their work accordingly.
- Backup: Always maintain a backup of your original repository before cleaning.
- Large Files: Consider using Git LFS (Large File Storage) for managing large files in the future.
- Documentation: Document the process and communicate with your team to avoid confusion and conflicts.

**Comment by timlinux** [comment]
Fine for me to do some cleaning, though I would not like to lose commit history - I and others did  a *lot* of work on this repo and the history is the only thing we have to show for it :-P

**Comment by haubourg** [comment]
> though I would not like to lose commit history 

From my experience of BG repo cleaner, you don't lose the history, yet it makes a push force and it is a mess for pending pull requests and branches.

**Comment by timlinux** [comment]
In that case, fine for me thanks @haubourg

**Pull request merged**
